### ISSUE TITLE
[초기설정] 

### ISSUE THREAD

**Issue by vvtkfkddl11** [Ajou-UniA/uniA-ios-app#1]
## 💡 Issue
프로젝트 초기설정

## 📝  todo
- [x] .gitignore 파일 추가
- [x] no storyboard 적용
- [x] SwiftLint 적용
- [x] View Controllers 추가
- [x] Snapkit, Then, Moya Package 추가
