### ISSUE TITLE
[초기설정]

### ISSUE THREAD

**Issue by vvtkfkddl11** [Ajou-UniA/uniA-ios-app#1]
## 💡 Issue
프로젝트 초기설정

## 📝  todo
- [ ] Snapkit, Then, Moya 패키지 추가
- [ ] View Controllers 추가
- [ ] no storyboard 적용
- [ ] .gitignore 파일 추가
- [ ] .gitignore에 .xcuserstate 추가
- [ ] swiftLint 적용
