### ISSUE TITLE
[FEAT]  MyPageView 구현

### ISSUE THREAD

**Issue by rudolfoss** [Ajou-UniA/uniA-ios-app#20]
## 💡 Issue

MyPageView 구현
## 📝  todo
- [x] reset password 구현!
- [ ] delete account  구현!
- [x] edit my profile 구현!
- [x] logout button 구현!
- [x] 전반적인 ui 짜기!

## 📸 Screenshot
<img width="248" alt="스크린샷 2023-04-02 오전 12 37 25" src="https://user-images.githubusercontent.com/79788182/229299307-e10197f6-8d4a-4cc4-a5ae-5f6663eb0f81.png">
