### ISSUE TITLE
[FEAT] Community 기초 작업

### ISSUE THREAD

**Issue by rudolfoss** [Ajou-UniA/uniA-ios-app#68]
## 💡 Issue
Community 기초 작업

## 📝  todo
- [x] FeedView 생성 및 기초 작업
- [x] PostView 생성 및 기초 작업
- [x] WriteView 생성 및 기초 작업
